name = "mml-face-license"
main = "src/index.ts"
compatibility_date = "2025-01-24"
workers_dev = true
preview_urls = false

[vars]
MODEL_PACK_OBJECT = "model-pack-v1.zip"
MODEL_PACK_VERSION = "1"
MODEL_PACK_SHA256 = "d2387b95b294fcbb0035be383a6a301065c8211c8ece9bcc7ecbd780f3be3e50"

[[r2_buckets]]
binding = "MODEL_BUCKET"
bucket_name = "mml-face-models"

[[d1_databases]]
binding = "LICENSE_DB"
database_name = "mml-face-license"
database_id = "2061cb1c-63ed-48ff-922d-894795a9370b"
migrations_dir = "migrations"
